name: Daily Update

on:
  push:
    branches: [master]
    paths:
      - "triggerUpdate"
  schedule:
    - cron: "15 14 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - run: npm run fhm

      - name: push
        run: |
          git config --global user.name 'Han Lin Yap'
          git config --global user.email 'codler@users.noreply.github.com'
          git add --all
          git commit -m "Github Action autocommit"
          git pull
          git push
